// <auto-generated />
using System;
using Cooper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooper.Data.Migrations
{
    [DbContext(typeof(CooperDbContext))]
    [Migration("20240206124926_CreateLikeTable")]
    partial class CreateLikeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooper.Data.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeGuid = new Guid("162ff745-7807-4b06-8660-5c7cc89a392f"),
                            Description = "Please take a good soccer photo",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            Name = "Best Soccer Picture",
                            Price = 11f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChallengeGuid = new Guid("520a4d3a-e6ce-458c-8c72-360a5ffc92eb"),
                            Description = "Please take a nice picture eating out",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            Name = "Best Steers Picture",
                            Price = 12f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ChallengeGuid = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "Please take a nice picture eating out",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 11,
                            Name = "Best Sunday Chill Picture",
                            Price = 13f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "You are the best",
                            Entity = 1,
                            EntityId = 7
                        },
                        new
                        {
                            Id = 2,
                            Body = "You are the best",
                            Entity = 1,
                            EntityId = 8
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UUID = new Guid("333afdfc-c836-4a17-b381-87ea385e4673")
                        },
                        new
                        {
                            Id = 12,
                            UUID = new Guid("9de47175-70d9-425b-a753-cac08c80798b")
                        },
                        new
                        {
                            Id = 13,
                            UUID = new Guid("44fa2768-5be1-4c9c-b222-2e9cdae8ef2c")
                        },
                        new
                        {
                            Id = 14,
                            UUID = new Guid("a7ba1bee-917b-4262-ae0e-a01eda194200")
                        },
                        new
                        {
                            Id = 15,
                            UUID = new Guid("d13369d5-eadb-41c6-a92b-003596227961")
                        },
                        new
                        {
                            Id = 2,
                            UUID = new Guid("ca4877dd-677c-43ba-bbca-6740d2205d05")
                        },
                        new
                        {
                            Id = 3,
                            UUID = new Guid("d4f4625c-fedb-4c63-aa36-3870f17074e0")
                        },
                        new
                        {
                            Id = 4,
                            UUID = new Guid("b599a3c6-23cd-4a13-a8bd-de0f5b0883b1")
                        },
                        new
                        {
                            Id = 5,
                            UUID = new Guid("0ff78f8e-93c0-4c8d-94c0-63f6ebc526eb")
                        },
                        new
                        {
                            Id = 6,
                            UUID = new Guid("c5b51598-0262-4bbb-a8fa-359ce695d1a4")
                        },
                        new
                        {
                            Id = 16,
                            UUID = new Guid("ef5afcc7-d41e-463f-8677-f4c318e12f36")
                        },
                        new
                        {
                            Id = 17,
                            UUID = new Guid("dc2dee3f-2eaa-4a82-84ef-83ff14f1af8c")
                        },
                        new
                        {
                            Id = 18,
                            UUID = new Guid("1dd28b15-3dc7-4da9-9dc5-4953b1a1a659")
                        },
                        new
                        {
                            Id = 19,
                            UUID = new Guid("a3bfed30-2d9a-42e9-9714-3e4be91ee0c2")
                        },
                        new
                        {
                            Id = 7,
                            UUID = new Guid("de5b3e25-5851-4da2-aa05-81ee862f5193")
                        },
                        new
                        {
                            Id = 8,
                            UUID = new Guid("70df340b-30ea-4c94-a72c-b97dcf304544")
                        },
                        new
                        {
                            Id = 9,
                            UUID = new Guid("7fbbdc31-a4c5-4fdc-99fe-bd871051efe0")
                        },
                        new
                        {
                            Id = 10,
                            UUID = new Guid("3781eaf6-c870-4901-99e1-0eb08dc9b045")
                        },
                        new
                        {
                            Id = 11,
                            UUID = new Guid("680d2b0f-cdc4-440a-a8f7-d94760958d2b")
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MediaGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Entity = 12,
                            EntityId = 2,
                            Link = "https://imageio.forbes.com/specials-images/imageserve/5d35eacaf1176b0008974b54/2020-Chevrolet-Corvette-Stingray/0x0.jpg?format=jpg&crop=4560,2565,x790,y784,safe&width=960",
                            MediaGuid = new Guid("9fb545ae-f3bf-4eee-b98d-2acc47254cf9"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 2,
                            Entity = 12,
                            EntityId = 3,
                            Link = "https://carwow-uk-wp-3.imgix.net/18015-MC20BluInfinito-scaled-e1666008987698.jpg",
                            MediaGuid = new Guid("d0b49135-e15a-47fd-91e5-4deffd694d9d"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 3,
                            Entity = 12,
                            EntityId = 4,
                            Link = "https://cdn.motor1.com/images/mgl/JO94P6/s1/most-expensive-cars-in-the-world.jpg",
                            MediaGuid = new Guid("24fac02b-7fe7-4cdf-8c41-c38a49941fcd"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 4,
                            Entity = 12,
                            EntityId = 5,
                            Link = "https://carwow-uk-wp-3.imgix.net/18015-MC20BluInfinito-scaled-e1666008987698.jpg",
                            MediaGuid = new Guid("56fed7da-19f3-4ad4-a26b-0baf7860d823"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 5,
                            Entity = 14,
                            EntityId = 6,
                            Link = "https://i.abcnewsfe.com/a/aae2e440-73a2-4252-a4c9-c7d27f0efda7/mcdonalds-gty-thg-230728_1690559943139_hpMain.jpg",
                            MediaGuid = new Guid("7fed571e-5496-4b1a-b0b8-7e06bef94f99"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 6,
                            Entity = 14,
                            EntityId = 7,
                            Link = "https://www.allrecipes.com/thmb/3YpMeC2Za5PkXZFnlNFaBOCtC3c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mcdonalds-store-front-4x3-0a58d7e370ce48f7b050203fd478c407.png",
                            MediaGuid = new Guid("c9d9eff2-12db-4dd4-9274-6d7107a4479f"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 7,
                            Entity = 15,
                            EntityId = 8,
                            Link = "https://www.foodandwine.com/thmb/K_t1B_xBKIKYm_ZoNIEqaBvuXcQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Burger-King-Everything-Seasoned-Bun-FT-BLOG0922-c8c7859b9c794c42af7700b5b957a874.jpg",
                            MediaGuid = new Guid("bf5233a9-912d-414d-8d22-4f4f55aed379"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 8,
                            Entity = 15,
                            EntityId = 9,
                            Link = "https://www.thestreet.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTg3NTA5NzAzMTQ2NzQzMzU2/burger-king-yeti-super-one-pound-beef-burger.jpg",
                            MediaGuid = new Guid("2c45a7ed-e1db-46a0-9031-c8740a2b2dc9"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 9,
                            Entity = 1,
                            EntityId = 16,
                            Link = "https://media-cdn.tripadvisor.com/media/photo-s/11/70/80/ac/chciken.jpg",
                            MediaGuid = new Guid("6911192f-41ed-4351-8490-12914c31847e"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 10,
                            Entity = 1,
                            EntityId = 17,
                            Link = "https://www.kimberley.co.za/wp-content/uploads/2022/01/38784_STEERS-AsPhande_Sharing_Meal_Promotion-20220113-KCP-SP-v1_00a.jpg",
                            MediaGuid = new Guid("52999905-513b-487b-b5da-7274a0c6e427"),
                            MediaType = 0
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Password");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "School Post",
                            EntityId = 1,
                            Likes = 12,
                            Title = "Steer Burger"
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = new Guid("520a4d3a-e6ce-458c-8c72-360a5ffc92eb"),
                            Description = "Sport Cars",
                            EntityId = 12,
                            Likes = 20,
                            Title = "Ball for Soccer Peeps"
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = new Guid("162ff745-7807-4b06-8660-5c7cc89a392f"),
                            Description = "Everything we care about",
                            EntityId = 13,
                            Likes = 25,
                            Title = "Hello Wold"
                        },
                        new
                        {
                            Id = 4,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "Best McDonald picture",
                            EntityId = 14,
                            Likes = 12,
                            Title = "Mc Donalds"
                        },
                        new
                        {
                            Id = 5,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "King Burger Tastes really good",
                            EntityId = 15,
                            Likes = 150,
                            Title = "King Burger"
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
