// <auto-generated />
using System;
using Cooper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooper.Data.Migrations
{
    [DbContext(typeof(CooperDbContext))]
    [Migration("20240128192401_AddSeedDataPostLinkedChallengeId")]
    partial class AddSeedDataPostLinkedChallengeId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooper.Data.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeGuid = new Guid("162ff745-7807-4b06-8660-5c7cc89a392f"),
                            Description = "Please take a good soccer photo",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            Name = "Best Soccer Picture",
                            Price = 11f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChallengeGuid = new Guid("520a4d3a-e6ce-458c-8c72-360a5ffc92eb"),
                            Description = "Please take a nice picture eating out",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            Name = "Best Steers Picture",
                            Price = 12f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ChallengeGuid = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "Please take a nice picture eating out",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 11,
                            Name = "Best Sunday Chill Picture",
                            Price = 13f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "You are the best",
                            Entity = 1,
                            EntityId = 7
                        },
                        new
                        {
                            Id = 2,
                            Body = "You are the best",
                            Entity = 1,
                            EntityId = 8
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UUID = new Guid("a8307e5d-516d-4a64-b803-150ae5345aca")
                        },
                        new
                        {
                            Id = 12,
                            UUID = new Guid("c2255524-508a-485c-a6e8-732aacd2fef2")
                        },
                        new
                        {
                            Id = 13,
                            UUID = new Guid("90975a8e-ddc8-4dc8-b483-57473913c87e")
                        },
                        new
                        {
                            Id = 2,
                            UUID = new Guid("70909fa2-6fbe-4583-9d64-9e2e32b409a0")
                        },
                        new
                        {
                            Id = 3,
                            UUID = new Guid("c2c02631-78de-4554-90d1-61bc0d7eb8dc")
                        },
                        new
                        {
                            Id = 4,
                            UUID = new Guid("4252b21b-a94d-49d7-8102-b2a9c64e8117")
                        },
                        new
                        {
                            Id = 5,
                            UUID = new Guid("61499f56-662e-48bf-9c21-59c0e19e78c3")
                        },
                        new
                        {
                            Id = 6,
                            UUID = new Guid("8a4c5a0b-0bc3-4875-baf5-3d9b8c04373b")
                        },
                        new
                        {
                            Id = 7,
                            UUID = new Guid("410f7ea6-e827-40f8-b517-9c7de5625b4b")
                        },
                        new
                        {
                            Id = 8,
                            UUID = new Guid("820bcef3-4009-4cee-9a54-4a3bebda4092")
                        },
                        new
                        {
                            Id = 9,
                            UUID = new Guid("278f14ff-9778-4207-860a-f2c185177310")
                        },
                        new
                        {
                            Id = 10,
                            UUID = new Guid("80de646c-99dc-4899-b14c-8064b8c26601")
                        },
                        new
                        {
                            Id = 11,
                            UUID = new Guid("75ad1522-e402-418d-a9a5-3f1976172c2d")
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MediaGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Entity = 1,
                            EntityId = 2,
                            Link = "https://imageio.forbes.com/specials-images/imageserve/5d35eacaf1176b0008974b54/2020-Chevrolet-Corvette-Stingray/0x0.jpg?format=jpg&crop=4560,2565,x790,y784,safe&width=960",
                            MediaGuid = new Guid("3811cb44-e945-4810-b423-70bbaadabdbb"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 2,
                            Entity = 1,
                            EntityId = 3,
                            Link = "https://carwow-uk-wp-3.imgix.net/18015-MC20BluInfinito-scaled-e1666008987698.jpg",
                            MediaGuid = new Guid("b2dbaca5-35fb-4a70-b38d-33014b458995"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 3,
                            Entity = 1,
                            EntityId = 4,
                            Link = "https://cdn.motor1.com/images/mgl/JO94P6/s1/most-expensive-cars-in-the-world.jpg",
                            MediaGuid = new Guid("23ac576e-2e93-4d78-9e39-f43ae35b37f4"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 4,
                            Entity = 1,
                            EntityId = 5,
                            Link = "https://carwow-uk-wp-3.imgix.net/18015-MC20BluInfinito-scaled-e1666008987698.jpg",
                            MediaGuid = new Guid("b4c2bf32-f50b-4a87-9a64-d36ff9240e61"),
                            MediaType = 0
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "School Post",
                            EntityId = 1,
                            Likes = 12,
                            Title = "Steer Burger"
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = new Guid("520a4d3a-e6ce-458c-8c72-360a5ffc92eb"),
                            Description = "Ronaldhino the best playyer",
                            EntityId = 12,
                            Likes = 20,
                            Title = "Ball for Soccer Peeps"
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = new Guid("162ff745-7807-4b06-8660-5c7cc89a392f"),
                            Description = "Everything we care about",
                            EntityId = 13,
                            Likes = 25,
                            Title = "Hello Wold"
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Username", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Username");
                });
#pragma warning restore 612, 618
        }
    }
}
