// <auto-generated />
using System;
using Cooper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cooper.Data.Migrations
{
    [DbContext(typeof(CooperDbContext))]
    [Migration("20240129075632_ChangeUsernameTableNameToUser")]
    partial class ChangeUsernameTableNameToUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cooper.Data.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Challenge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeGuid = new Guid("162ff745-7807-4b06-8660-5c7cc89a392f"),
                            Description = "Please take a good soccer photo",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            Name = "Best Soccer Picture",
                            Price = 11f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChallengeGuid = new Guid("520a4d3a-e6ce-458c-8c72-360a5ffc92eb"),
                            Description = "Please take a nice picture eating out",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            Name = "Best Steers Picture",
                            Price = 12f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ChallengeGuid = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "Please take a nice picture eating out",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 11,
                            Name = "Best Sunday Chill Picture",
                            Price = 13f,
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "You are the best",
                            Entity = 1,
                            EntityId = 7
                        },
                        new
                        {
                            Id = 2,
                            Body = "You are the best",
                            Entity = 1,
                            EntityId = 8
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UUID = new Guid("4a6c3d56-1dd3-46f4-bc32-c0989abd37ad")
                        },
                        new
                        {
                            Id = 12,
                            UUID = new Guid("c2743596-76d2-4761-ae9e-1187268da476")
                        },
                        new
                        {
                            Id = 13,
                            UUID = new Guid("3a4d2fa2-f5d9-43eb-9f4c-704d6e2d7522")
                        },
                        new
                        {
                            Id = 14,
                            UUID = new Guid("bf9360df-2f51-4786-aaaa-2e16dd3d4b54")
                        },
                        new
                        {
                            Id = 15,
                            UUID = new Guid("e9f1e3bf-485e-4be7-9736-d42b2e62375a")
                        },
                        new
                        {
                            Id = 2,
                            UUID = new Guid("f3f6828b-ee7d-4a36-ad66-2107aac3421a")
                        },
                        new
                        {
                            Id = 3,
                            UUID = new Guid("8c67c58c-50b5-4882-ac19-0d4bf034b8ad")
                        },
                        new
                        {
                            Id = 4,
                            UUID = new Guid("f2e9d792-7df9-4af2-99f9-0062c2bd037a")
                        },
                        new
                        {
                            Id = 5,
                            UUID = new Guid("06c006bb-1dae-4a36-9f57-f6f0fc83f685")
                        },
                        new
                        {
                            Id = 6,
                            UUID = new Guid("77e9d4c5-dae4-4acc-82ba-04f5e6372dde")
                        },
                        new
                        {
                            Id = 16,
                            UUID = new Guid("ae09db8e-2c2b-4b71-84e5-55d436638b31")
                        },
                        new
                        {
                            Id = 17,
                            UUID = new Guid("2588ffe0-fc48-417f-a5a4-835a8ec4adcd")
                        },
                        new
                        {
                            Id = 18,
                            UUID = new Guid("098a9339-88ef-4631-a3a4-5de65e9869be")
                        },
                        new
                        {
                            Id = 19,
                            UUID = new Guid("c4ab4e6c-b1fb-4fe9-8f9c-be14f57551a1")
                        },
                        new
                        {
                            Id = 7,
                            UUID = new Guid("1769bffa-ecff-4d4d-9df1-57e020aae5aa")
                        },
                        new
                        {
                            Id = 8,
                            UUID = new Guid("d6d205f0-8ad9-4d45-8258-089eb6371175")
                        },
                        new
                        {
                            Id = 9,
                            UUID = new Guid("41174498-7afe-4ff6-ad9c-d056ae618e49")
                        },
                        new
                        {
                            Id = 10,
                            UUID = new Guid("431802af-9df1-465b-a240-7b277088ab2c")
                        },
                        new
                        {
                            Id = 11,
                            UUID = new Guid("2a93ae7f-f0b8-4226-929c-a3c6775f4b51")
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Entity")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MediaGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Entity = 12,
                            EntityId = 2,
                            Link = "https://imageio.forbes.com/specials-images/imageserve/5d35eacaf1176b0008974b54/2020-Chevrolet-Corvette-Stingray/0x0.jpg?format=jpg&crop=4560,2565,x790,y784,safe&width=960",
                            MediaGuid = new Guid("e68bac28-3d61-4bf5-9624-28a11e39751c"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 2,
                            Entity = 12,
                            EntityId = 3,
                            Link = "https://carwow-uk-wp-3.imgix.net/18015-MC20BluInfinito-scaled-e1666008987698.jpg",
                            MediaGuid = new Guid("7b800aa6-a349-413e-be8d-8aab827614eb"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 3,
                            Entity = 12,
                            EntityId = 4,
                            Link = "https://cdn.motor1.com/images/mgl/JO94P6/s1/most-expensive-cars-in-the-world.jpg",
                            MediaGuid = new Guid("5678e46c-8313-48b9-9467-71458782aee0"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 4,
                            Entity = 12,
                            EntityId = 5,
                            Link = "https://carwow-uk-wp-3.imgix.net/18015-MC20BluInfinito-scaled-e1666008987698.jpg",
                            MediaGuid = new Guid("f45348ed-43da-461e-b760-7c9a470a27bb"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 5,
                            Entity = 14,
                            EntityId = 6,
                            Link = "https://i.abcnewsfe.com/a/aae2e440-73a2-4252-a4c9-c7d27f0efda7/mcdonalds-gty-thg-230728_1690559943139_hpMain.jpg",
                            MediaGuid = new Guid("78cd9b66-bd0b-4df5-8f2c-371c20ff90bd"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 6,
                            Entity = 14,
                            EntityId = 7,
                            Link = "https://www.allrecipes.com/thmb/3YpMeC2Za5PkXZFnlNFaBOCtC3c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/mcdonalds-store-front-4x3-0a58d7e370ce48f7b050203fd478c407.png",
                            MediaGuid = new Guid("88fee955-f781-4b1d-ac98-7e0f31ff207d"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 7,
                            Entity = 15,
                            EntityId = 8,
                            Link = "https://www.foodandwine.com/thmb/K_t1B_xBKIKYm_ZoNIEqaBvuXcQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Burger-King-Everything-Seasoned-Bun-FT-BLOG0922-c8c7859b9c794c42af7700b5b957a874.jpg",
                            MediaGuid = new Guid("f5ee9568-43fe-47d8-bef9-97caf2df3650"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 8,
                            Entity = 15,
                            EntityId = 9,
                            Link = "https://www.thestreet.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTg3NTA5NzAzMTQ2NzQzMzU2/burger-king-yeti-super-one-pound-beef-burger.jpg",
                            MediaGuid = new Guid("64812249-3c1d-42f0-9d47-91733a20c5c9"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 9,
                            Entity = 1,
                            EntityId = 16,
                            Link = "https://media-cdn.tripadvisor.com/media/photo-s/11/70/80/ac/chciken.jpg",
                            MediaGuid = new Guid("7bcb74bf-8fcd-4d73-a45a-74bc4ca0858c"),
                            MediaType = 0
                        },
                        new
                        {
                            Id = 10,
                            Entity = 1,
                            EntityId = 17,
                            Link = "https://www.kimberley.co.za/wp-content/uploads/2022/01/38784_STEERS-AsPhande_Sharing_Meal_Promotion-20220113-KCP-SP-v1_00a.jpg",
                            MediaGuid = new Guid("2e48ce70-18a0-4816-85d0-f51938391339"),
                            MediaType = 0
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Cooper.Data.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "School Post",
                            EntityId = 1,
                            Likes = 12,
                            Title = "Steer Burger"
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = new Guid("520a4d3a-e6ce-458c-8c72-360a5ffc92eb"),
                            Description = "Sport Cars",
                            EntityId = 12,
                            Likes = 20,
                            Title = "Ball for Soccer Peeps"
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = new Guid("162ff745-7807-4b06-8660-5c7cc89a392f"),
                            Description = "Everything we care about",
                            EntityId = 13,
                            Likes = 25,
                            Title = "Hello Wold"
                        },
                        new
                        {
                            Id = 4,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "Best McDonald picture",
                            EntityId = 14,
                            Likes = 12,
                            Title = "Mc Donalds"
                        },
                        new
                        {
                            Id = 5,
                            ChallengeId = new Guid("a3bb21c7-9ea2-4c9b-9811-e3526856d05b"),
                            Description = "King Burger Tastes really good",
                            EntityId = 15,
                            Likes = 150,
                            Title = "King Burger"
                        });
                });

            modelBuilder.Entity("Cooper.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("EntityId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
